### ISSUE TITLE
search-in parameter seems unused in crispin.core/cfg

### ISSUE THREAD

**Issue by borkdude** [dunaj-project/crispin#2]
The `crispin.core/cfg` function has an unused argument `search-in`. What is this supposed to do?

**Comment by wagjo** [comment]
It was to include additional config.clj files that could be somewhere on the classpath. The feature was removed but the argument was kept as it'd break the API. https://github.com/dunaj-project/crispin/blob/9f297147c9a1cc3f417589ffc6cef7136800a223/src/crispin/core.clj#L281

**Comment by borkdude** [comment]
OK!
